# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "will maclean"
email: "willmaclean@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  "Linguistic AI, code, philosophy, etc. "
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@w_amac"
github_username:  "willmaclean"

I am a data scientist currently working on AI for cardiac health. I research epistemic and semantic uncertainty in the language of radiology reporting. See my github for relevant code.

I am also interested in AI for ecology and bio-systems. What can we save...

Formerly a student of eighteenth-century philosophy. I am a lapsed arts student stumbling through STEM. I wrote a dissertation on the third Earl of Shaftesbury (1671-1713). I'm always up for a chat about the history of moral philosophy, eighteenth-century politics of land, the British abolition movement, and Bernard Williams. 

I maintain an email letter of dubious merit at walfred.substack.com.

My twitter is @willlmaclean.

Reach my email at willmaclean (at) gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
